id: f5638299-05ad-4f56-85bb-3f2787068422
version: 16
vcShouldKeepItemLegacyProdMachine: false
name: 'AccessData: Collect Endpoint Memory'
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 9599d31e-9c48-451a-8644-fa21f7161ecd
    type: start
    task:
      id: 9599d31e-9c48-451a-8644-fa21f7161ecd
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: ab8815ca-0fe1-4524-8317-185ec8f44c0e
    type: regular
    task:
      id: ab8815ca-0fe1-4524-8317-185ec8f44c0e
      version: -1
      name: AccessDataCreateCase
      description: Creates a New Case within the AccessData Platform.
      scriptName: AccessDataCreateCase
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 2fce28f6-d5dd-4fce-8928-192d3857cfd2
    type: regular
    task:
      id: 2fce28f6-d5dd-4fce-8928-192d3857cfd2
      version: -1
      name: AccessDataAcquireMemory
      description: Gathers a image of memory from the endpoint and stores it in the
        case directory.
      scriptName: AccessDataAcquireMemory
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      caseid:
        simple: ${id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 4c38f0ad-ceac-4cc9-8df1-6039c844110c
    type: regular
    task:
      id: 4c38f0ad-ceac-4cc9-8df1-6039c844110c
      version: -1
      name: AccessDataAwaitJob
      description: Awaits an end status for the specified job and returns when complete.
      scriptName: AccessDataAwaitJob
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      caseid:
        simple: ${id}
      jobid:
        simple: ${id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 635,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: PROTOCOL
  value: {}
  required: true
  description: ""
  playbookInputQuery: null
- key: SERVER
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: PORT
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: APIKEY
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
outputs: []
